---
title: "Plotly"
author: "ht2448 cbh2134"
date: "11/1/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Dataset

```{r}
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(readxl)
library(plotly)
```


### The data set is NYC Restaurant dataset. And we've radonmly taken 20000 samples from the whole dataset.



Import and Clean data. 

```{r}
nyc_inspections = read_csv("./DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", 
                           col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>% 
  filter(grade %in% c("A", "B", "C")) %>% 
  mutate(inspection_num = row_number(),   
         boro = str_to_title(boro)) %>% 
  select(inspection_num, boro, grade, score, critical_flag, dba, cuisine_description, zipcode, violation_description)

# take 20k random sample
set.seed(123)
nyc_subdata = nyc_inspections[sample(nrow(nyc_inspections), 20000), ]
```

### Plotly Scatterplot

```{r}
scatter_ggplot = nyc_subdata %>%
  ggplot(aes(x = zipcode, y = score, color = zipcode)) +
  geom_point(alpha = 0.25) +
  scale_color_viridis() +
  coord_cartesian() + labs(title = "Restaurant Score for Zipcodes", x = "Zipcodes", y = "Restaurant Score") +
  theme_classic()
ggplotly(scatter_ggplot)
```


### Plotly boxplot

```{r}
box_ggplot =
nyc_subdata %>% 
  filter(cuisine_description %in% c("American", "Chinese","Italian","Pizza","Mexican")) %>% 
   mutate(cuisine_description = fct_reorder(cuisine_description, score)) %>%
ggplot(aes(x = cuisine_description, y = score, group = cuisine_description)) + geom_boxplot(aes(color = cuisine_description)) + labs(title = "Boxplot of the restaurant score for Five cusine type in NYC", x = "cuisine type", y = "Restuarant Score") + theme_classic() + theme(axis.text.x = element_text(hjust = 1), plot.title = element_text(hjust = 0.5))
ggplotly(box_ggplot)
```

### Plotly bar chart, Top 5 cuisine types

```{r}
nyc_subdata %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  top_n(5) %>%
  plot_ly(x = ~cuisine_description, y = ~n, color = ~cuisine_description, type = "bar", colors = "Set2")
```

